image: microsoft/dotnet:latest

stages:
#- build
#- test
- deploy

#build:
#  stage: build
#  script:
#  - dotnet build

#test:
#  stage: test
#  script: 
#  - dotnet test
        
deploy:
  stage: deploy
  script:
  - cd BandPageGenerator
  - dotnet publish -c Release
  - tar -czf $CI_COMMIT_TAG.tar.gz ./bin/Release/netcoreapp2.2/publish
  artifacts:
    paths:
    - $CI_COMMIT_TAG.tar.gz  
  only:
    - tags
  #except:
  #  - branches