image: microsoft/dotnet:latest

stages:
- test
- deploy

test:
  stage: test
  script: 
  - dotnet test
        
deploy:
  stage: deploy
  script:
  - cd BandPageGenerator
  - dotnet publish -c Release
  - tar -czf ../$CI_COMMIT_TAG.tar.gz --directory="./bin/Release/netcoreapp2.2/" publish
  - cd "../"
  - chmod +x ./release.sh
  - ./release.sh
  only:
    - tags
  except:
    - branches