image: microsoft/dotnet:latest

stages:
- test
- deploy

test:
  stage: test
  script: 
  - "dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover"
  - "curl -s https://codecov.io/bash > codecov"
  - chmod +x codecov
  - ./codecov -f "Tests/coverage.opencover.xml" -t $CODECOV_UPLOAD_TOKEN
  only:
  - develop
  - master
        
deploy:
  stage: deploy
  script:
  - cd BandPageGenerator
  - dotnet publish -c Release
  - tar -czf ../$CI_COMMIT_TAG.tar.gz --directory="./bin/Release/netcoreapp2.2/" publish
  - cd "../"
  - chmod +x ./release.sh
  - ./release.sh
  only:
    - tags
  except:
    - branches