image: microsoft/dotnet:latest

stages:
- build
- test
- deploy

before_script:
- dotnet restore

build:
  stage: build
  script:
  - dotnet build

test:
  stage: test
  script: 
  - dotnet test
        
deploy:
  stage: deploy
  script:
  - cd BandPageGenerator
  - dotnet publish -c Release
  - zip -r $CI_COMMIT_TAG.zip BandPageGenerator/bin/Release/netcoreapp2.2/publish
  artifacts:
    paths:
    - $CI_COMMIT_TAG.zip  
  only:
    - tags
  except:
    - branches